/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationExchangeTokenRequest
 */
public class AuthenticationExchangeTokenRequestTest {
    private final AuthenticationExchangeTokenRequest model = new AuthenticationExchangeTokenRequest();

    /**
     * Model tests for AuthenticationExchangeTokenRequest
     */
    @Test
    public void testAuthenticationExchangeTokenRequest() {
        // TODO: test AuthenticationExchangeTokenRequest
    }

    /**
     * Test the property 'publicToken'
     */
    @Test
    public void publicTokenTest() {
        // TODO: test publicToken
    }

}
