/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ConnectionsCreateCustomConnectionRequestBackfill;
import com.konfigthis.client.model.ConnectionsCreateCustomConnectionRequestCompany;
import com.konfigthis.client.model.ConnectionsCreateCustomConnectionRequestCredentials;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConnectionsCreateCustomConnectionRequest
 */
public class ConnectionsCreateCustomConnectionRequestTest {
    private final ConnectionsCreateCustomConnectionRequest model = new ConnectionsCreateCustomConnectionRequest();

    /**
     * Model tests for ConnectionsCreateCustomConnectionRequest
     */
    @Test
    public void testConnectionsCreateCustomConnectionRequest() {
        // TODO: test ConnectionsCreateCustomConnectionRequest
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'backfill'
     */
    @Test
    public void backfillTest() {
        // TODO: test backfill
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    public void credentialsTest() {
        // TODO: test credentials
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'syncMode'
     */
    @Test
    public void syncModeTest() {
        // TODO: test syncMode
    }

}
