/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DevicesApi
 */
@Disabled
public class DevicesApiTest {

    private static DevicesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DevicesApi(apiClient);
    }

    /**
     * List Devices
     *
     * List all devices in the connected account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllDevicesTest() throws ApiException {
        String cursor = null;
        String limit = null;
        String modifiedAfter = null;
        String modifiedBefore = null;
        String raw = null;
        String connectionToken = null;
        api.getAllDevices()
                .cursor(cursor)
                .limit(limit)
                .modifiedAfter(modifiedAfter)
                .modifiedBefore(modifiedBefore)
                .raw(raw)
                .connectionToken(connectionToken)
                .execute();
        // TODO: test validations
    }

}
