/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IftaApi
 */
@Disabled
public class IftaApiTest {

    private static IftaApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new IftaApi(apiClient);
    }

    /**
     * Get IFTA Summary
     *
     * Get all vehicle IFTA reports for the requested time span.  Currently can only increment by full months.   _Note:_ data may change for a few days after the month. We will continue to update those reports to ensure you get accurate results.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMonthlyReportsTest() throws ApiException {
        String cursor = null;
        String expand = null;
        String raw = null;
        String startMonth = null;
        String endMonth = null;
        String groupBy = null;
        String connectionToken = null;
        api.getMonthlyReports()
                .cursor(cursor)
                .expand(expand)
                .raw(raw)
                .startMonth(startMonth)
                .endMonth(endMonth)
                .groupBy(groupBy)
                .connectionToken(connectionToken)
                .execute();
        // TODO: test validations
    }

}
