/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.AuthenticationExchangeTokenRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class AuthenticationApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthenticationApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public AuthenticationApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call exchangeTokenCall(AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = authenticationExchangeTokenRequest;

        // create path and map variables
        String localVarPath = "/public-token/exchange";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call exchangeTokenValidateBeforeCall(AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest, final ApiCallback _callback) throws ApiException {
        return exchangeTokenCall(authenticationExchangeTokenRequest, _callback);

    }


    private ApiResponse<Void> exchangeTokenWithHttpInfo(AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest) throws ApiException {
        okhttp3.Call localVarCall = exchangeTokenValidateBeforeCall(authenticationExchangeTokenRequest, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call exchangeTokenAsync(AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = exchangeTokenValidateBeforeCall(authenticationExchangeTokenRequest, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class ExchangeTokenRequestBuilder {
        private String publicToken;

        private ExchangeTokenRequestBuilder() {
        }

        /**
         * Set publicToken
         * @param publicToken  (optional)
         * @return ExchangeTokenRequestBuilder
         */
        public ExchangeTokenRequestBuilder publicToken(String publicToken) {
            this.publicToken = publicToken;
            return this;
        }
        
        /**
         * Build call for exchangeToken
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest = buildBodyParams();
            return exchangeTokenCall(authenticationExchangeTokenRequest, _callback);
        }

        private AuthenticationExchangeTokenRequest buildBodyParams() {
            AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest = new AuthenticationExchangeTokenRequest();
            authenticationExchangeTokenRequest.publicToken(this.publicToken);
            return authenticationExchangeTokenRequest;
        }

        /**
         * Execute exchangeToken request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest = buildBodyParams();
            exchangeTokenWithHttpInfo(authenticationExchangeTokenRequest);
        }

        /**
         * Execute exchangeToken request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest = buildBodyParams();
            return exchangeTokenWithHttpInfo(authenticationExchangeTokenRequest);
        }

        /**
         * Execute exchangeToken request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            AuthenticationExchangeTokenRequest authenticationExchangeTokenRequest = buildBodyParams();
            return exchangeTokenAsync(authenticationExchangeTokenRequest, _callback);
        }
    }

    /**
     * Public Token Exchange
     * Exchange the &#x60;publicToken&#x60; returned by our hosted authentication flow for a long lived connection token that will be used when requesting data from a customer&#39;s TSP.
     * @return ExchangeTokenRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ExchangeTokenRequestBuilder exchangeToken() throws IllegalArgumentException {
        return new ExchangeTokenRequestBuilder();
    }
}
