/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class IftaApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public IftaApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public IftaApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getMonthlyReportsCall(String cursor, String expand, String raw, String startMonth, String endMonth, String groupBy, String connectionToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/ifta/summary";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (expand != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("expand", expand));
        }

        if (raw != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("raw", raw));
        }

        if (startMonth != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("startMonth", startMonth));
        }

        if (endMonth != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("endMonth", endMonth));
        }

        if (groupBy != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("groupBy", groupBy));
        }

        if (connectionToken != null) {
            localVarHeaderParams.put("connection-token", localVarApiClient.parameterToString(connectionToken));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMonthlyReportsValidateBeforeCall(String cursor, String expand, String raw, String startMonth, String endMonth, String groupBy, String connectionToken, final ApiCallback _callback) throws ApiException {
        return getMonthlyReportsCall(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken, _callback);

    }


    private ApiResponse<Void> getMonthlyReportsWithHttpInfo(String cursor, String expand, String raw, String startMonth, String endMonth, String groupBy, String connectionToken) throws ApiException {
        okhttp3.Call localVarCall = getMonthlyReportsValidateBeforeCall(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getMonthlyReportsAsync(String cursor, String expand, String raw, String startMonth, String endMonth, String groupBy, String connectionToken, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMonthlyReportsValidateBeforeCall(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetMonthlyReportsRequestBuilder {
        private String cursor;
        private String expand;
        private String raw;
        private String startMonth;
        private String endMonth;
        private String groupBy;
        private String connectionToken;

        private GetMonthlyReportsRequestBuilder() {
        }

        /**
         * Set cursor
         * @param cursor Pagination cursor to start requests from (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set expand
         * @param expand Expand resources in the returned response (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder expand(String expand) {
            this.expand = expand;
            return this;
        }
        
        /**
         * Set raw
         * @param raw Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified. (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder raw(String raw) {
            this.raw = raw;
            return this;
        }
        
        /**
         * Set startMonth
         * @param startMonth (Required) The month from which to start including vehicle reports (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder startMonth(String startMonth) {
            this.startMonth = startMonth;
            return this;
        }
        
        /**
         * Set endMonth
         * @param endMonth (Required) Include vehicle reports up to and including this month (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder endMonth(String endMonth) {
            this.endMonth = endMonth;
            return this;
        }
        
        /**
         * Set groupBy
         * @param groupBy Computes the total distance traversed within a specified month range, with the results grouped by either jurisdiction, vehicle, or both. If no grouping parameter is provided, the default grouping is &#x60;vehicle,jurisdiction&#x60;. (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder groupBy(String groupBy) {
            this.groupBy = groupBy;
            return this;
        }
        
        /**
         * Set connectionToken
         * @param connectionToken (Required) The token returned when a user authenticated their account. This authorizes access to a specific account. (optional)
         * @return GetMonthlyReportsRequestBuilder
         */
        public GetMonthlyReportsRequestBuilder connectionToken(String connectionToken) {
            this.connectionToken = connectionToken;
            return this;
        }
        
        /**
         * Build call for getMonthlyReports
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getMonthlyReportsCall(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken, _callback);
        }


        /**
         * Execute getMonthlyReports request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getMonthlyReportsWithHttpInfo(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken);
        }

        /**
         * Execute getMonthlyReports request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getMonthlyReportsWithHttpInfo(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken);
        }

        /**
         * Execute getMonthlyReports request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getMonthlyReportsAsync(cursor, expand, raw, startMonth, endMonth, groupBy, connectionToken, _callback);
        }
    }

    /**
     * Get IFTA Summary
     * Get all vehicle IFTA reports for the requested time span.  Currently can only increment by full months.   _Note:_ data may change for a few days after the month. We will continue to update those reports to ensure you get accurate results.
     * @return GetMonthlyReportsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public GetMonthlyReportsRequestBuilder getMonthlyReports() throws IllegalArgumentException {
        return new GetMonthlyReportsRequestBuilder();
    }
}
