/*
 * Terminal API
 * Terminal is a unified API that makes it easy to integrate with the leading telematics service providers.  Contact Support:  Name: Terminal  Email: connect@withterminal.com
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class TripsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public TripsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public TripsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getAllTripsCall(String cursor, String limit, String modifiedAfter, String modifiedBefore, String startedAfter, String startedBefore, String endedAfter, String endedBefore, String driverIds, String vehicleIds, String raw, String expand, String connectionToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/trips";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (modifiedAfter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("modifiedAfter", modifiedAfter));
        }

        if (modifiedBefore != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("modifiedBefore", modifiedBefore));
        }

        if (startedAfter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("startedAfter", startedAfter));
        }

        if (startedBefore != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("startedBefore", startedBefore));
        }

        if (endedAfter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("endedAfter", endedAfter));
        }

        if (endedBefore != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("endedBefore", endedBefore));
        }

        if (driverIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("driverIds", driverIds));
        }

        if (vehicleIds != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("vehicleIds", vehicleIds));
        }

        if (raw != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("raw", raw));
        }

        if (expand != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("expand", expand));
        }

        if (connectionToken != null) {
            localVarHeaderParams.put("connection-token", localVarApiClient.parameterToString(connectionToken));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllTripsValidateBeforeCall(String cursor, String limit, String modifiedAfter, String modifiedBefore, String startedAfter, String startedBefore, String endedAfter, String endedBefore, String driverIds, String vehicleIds, String raw, String expand, String connectionToken, final ApiCallback _callback) throws ApiException {
        return getAllTripsCall(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken, _callback);

    }


    private ApiResponse<Void> getAllTripsWithHttpInfo(String cursor, String limit, String modifiedAfter, String modifiedBefore, String startedAfter, String startedBefore, String endedAfter, String endedBefore, String driverIds, String vehicleIds, String raw, String expand, String connectionToken) throws ApiException {
        okhttp3.Call localVarCall = getAllTripsValidateBeforeCall(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call getAllTripsAsync(String cursor, String limit, String modifiedAfter, String modifiedBefore, String startedAfter, String startedBefore, String endedAfter, String endedBefore, String driverIds, String vehicleIds, String raw, String expand, String connectionToken, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllTripsValidateBeforeCall(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class GetAllTripsRequestBuilder {
        private String cursor;
        private String limit;
        private String modifiedAfter;
        private String modifiedBefore;
        private String startedAfter;
        private String startedBefore;
        private String endedAfter;
        private String endedBefore;
        private String driverIds;
        private String vehicleIds;
        private String raw;
        private String expand;
        private String connectionToken;

        private GetAllTripsRequestBuilder() {
        }

        /**
         * Set cursor
         * @param cursor Pagination cursor to start requests from (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit The maximum number of results to return in a page. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder limit(String limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set modifiedAfter
         * @param modifiedAfter Only include records that were last modified after a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder modifiedAfter(String modifiedAfter) {
            this.modifiedAfter = modifiedAfter;
            return this;
        }
        
        /**
         * Set modifiedBefore
         * @param modifiedBefore Only include records that were last modified before a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder modifiedBefore(String modifiedBefore) {
            this.modifiedBefore = modifiedBefore;
            return this;
        }
        
        /**
         * Set startedAfter
         * @param startedAfter Only include trips that started after a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder startedAfter(String startedAfter) {
            this.startedAfter = startedAfter;
            return this;
        }
        
        /**
         * Set startedBefore
         * @param startedBefore Only include trips that started before a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder startedBefore(String startedBefore) {
            this.startedBefore = startedBefore;
            return this;
        }
        
        /**
         * Set endedAfter
         * @param endedAfter Only include trips that ended after a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder endedAfter(String endedAfter) {
            this.endedAfter = endedAfter;
            return this;
        }
        
        /**
         * Set endedBefore
         * @param endedBefore Only include trips that ended before a provided date. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder endedBefore(String endedBefore) {
            this.endedBefore = endedBefore;
            return this;
        }
        
        /**
         * Set driverIds
         * @param driverIds Comma separated list of driver IDs to filter for (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder driverIds(String driverIds) {
            this.driverIds = driverIds;
            return this;
        }
        
        /**
         * Set vehicleIds
         * @param vehicleIds Comma separated list of vehicle IDs to filter for (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder vehicleIds(String vehicleIds) {
            this.vehicleIds = vehicleIds;
            return this;
        }
        
        /**
         * Set raw
         * @param raw Include raw responses used to normalize model. Used for debugging or accessing unique properties that are not unified. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder raw(String raw) {
            this.raw = raw;
            return this;
        }
        
        /**
         * Set expand
         * @param expand Expand resources in the returned response (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder expand(String expand) {
            this.expand = expand;
            return this;
        }
        
        /**
         * Set connectionToken
         * @param connectionToken (Required) The token returned when a user authenticated their account. This authorizes access to a specific account. (optional)
         * @return GetAllTripsRequestBuilder
         */
        public GetAllTripsRequestBuilder connectionToken(String connectionToken) {
            this.connectionToken = connectionToken;
            return this;
        }
        
        /**
         * Build call for getAllTrips
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getAllTripsCall(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken, _callback);
        }


        /**
         * Execute getAllTrips request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            getAllTripsWithHttpInfo(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken);
        }

        /**
         * Execute getAllTrips request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return getAllTripsWithHttpInfo(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken);
        }

        /**
         * Execute getAllTrips request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return getAllTripsAsync(cursor, limit, modifiedAfter, modifiedBefore, startedAfter, startedBefore, endedAfter, endedBefore, driverIds, vehicleIds, raw, expand, connectionToken, _callback);
        }
    }

    /**
     * List Trips
     * List all trips in the connected account. Trips define a period of time where a vehicle is in motion.
     * @return GetAllTripsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public GetAllTripsRequestBuilder getAllTrips() throws IllegalArgumentException {
        return new GetAllTripsRequestBuilder();
    }
}
